name: CI

on:
  push:
    branches:
      - "main"
      - "github-actions"
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      CI: true
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test

      - name: Build Applications
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.ACCESS_TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
